### ISSUE TITLE
Lords of the Fallen 2.0 Unable to complete shader compilation with Cxpatch 0.6.3

### ISSUE THREAD

**Issue by nogoo** [italomandara/CXPatcher#243]
CrossOver 25.0.1 + CXpatch 0.6.3
Lords of the Fallen 2.0 Unable to complete shader compilation

Original CrossOver 25 Ok~

**Comment by italomandara** [comment]
I can't really work on it if you don't give me more info, what translation layer? what machine/os ? any logs? with options did you use when you patched?

**Comment by nogoo** [comment]
M3 Pro Macos 15.4.1 
CrossOver 25.0.1 + D3DMetal+MSync
Cxpatch 0.6.3: 
Patch MoltenVK: default
DXMT:0.50
Patch DXVK(No matter try yes/no, it all fail.  the game Lords of the Fallen 2.0 still Unable to complete shader compilation)
Others default~

Original Crossover 25.0.1  + D3DMetal + MSync:  Okay~

**Comment by nogoo** [comment]
I haven't found any issues with other games yet, such as Elden/Cyberpunk/RDR2, and so on. The strange problem is that in the past, when encountering other games or programs crashing, Crossover would display a Windbg debugging screen with error messages. However, after executing a shader compilation with no changes to the screen, Lords of the Fallen 2.0 crashes directly without any Windbg messages appearing, and no errlogs were found in the game directory

**Comment by italomandara** [comment]
I assume You're running the game on patched CX using the same translation layer (D3DMetal)

**Comment by nogoo** [comment]
Okay, I tried different versions of advanced options (0.6.1, 0.6.2, 0.6.3) and CrossOver25/25.0.1 again, and the problem was based on

**Comment by italomandara** [comment]
based on what in particular?

**Comment by italomandara** [comment]
Can you try if this build fixes your problem?
https://github.com/italomandara/CXPatcher/releases/download/v0.6.3/CXPatcher.app.zip

also just to check if everything was patched correctly check cxplog.txt inside Crossover_patched/Contents

**Comment by nogoo** [comment]
app version is ok: 25.0.1
it's a crossover app
file:///Users/wooki/Applications/CrossOver_original.app
Release version detected, copying DXMT
/Volumes/WinGo/PCGames/CrossOverApp/v0.50/x86_64-unix/winemetal.so copied
/Volumes/WinGo/PCGames/CrossOverApp/v0.50/x86_64-windows/winemetal.dll copied
/Volumes/WinGo/PCGames/CrossOverApp/v0.50/x86_64-windows/dxgi.dll copied
/Volumes/WinGo/PCGames/CrossOverApp/v0.50/x86_64-windows/d3d11.dll copied
/Volumes/WinGo/PCGames/CrossOverApp/v0.50/x86_64-windows/d3d10core.dll copied
/Volumes/WinGo/PCGames/CrossOverApp/v0.50/i386-windows/winemetal.dll copied
/Volumes/WinGo/PCGames/CrossOverApp/v0.50/i386-windows/dxgi.dll copied
/Volumes/WinGo/PCGames/CrossOverApp/v0.50/i386-windows/d3d11.dll copied
/Volumes/WinGo/PCGames/CrossOverApp/v0.50/i386-windows/d3d10core.dll copied
Crossover/lib64/libMoltenVK.dylib copied
Crossover/lib/dxvk/i386-windows/d3d10core.dll copied
Crossover/lib/dxvk/i386-windows/d3d11.dll copied
Crossover/lib/dxvk/x86_64-windows/d3d10core.dll copied
Crossover/lib/dxvk/x86_64-windows/d3d11.dll copied
/Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib/wine/i386-windows/winemetal.dll does not exist!
Crossover/lib/wine/i386-windows/winemetal.dll copied
Crossover/lib/wine/x86_64-unix/winegstreamer.so copied
Crossover/lib/wine/x86_64-windows/winemetal.dll copied
Crossover/share/wine/wine.inf copied
removing /Users/wooki/Applications/CrossOver.app/Contents/CodeResources
removing /Users/wooki/Applications/CrossOver.app/Contents/_CodeSignature
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgmodule-2.0.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgthread-2.0.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstplayer-1.0.0.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstaudio-1.0.0.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstsdp-1.0.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstmpegts-1.0.0.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstnet-1.0.0.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstmpegts-1.0.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstrtsp-1.0.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libffi.8.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstreamer-1.0.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgsttranscoder-1.0.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstisoff-1.0.0.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstphotography-1.0.0.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstsdp-1.0.0.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstplay-1.0.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstplay-1.0.0.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgobject-2.0.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstreamer-1.0.0.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstcodecs-1.0.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libpcre2-8.0.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstwebrtc-1.0.0.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstcontroller-1.0.0.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstcodecparsers-1.0.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstbadaudio-1.0.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libglib-2.0.0.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstrtp-1.0.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstwebrtc-1.0.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgsttag-1.0.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstinsertbin-1.0.0.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstisoff-1.0.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstfft-1.0.0.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstbadaudio-1.0.0.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgio-2.0.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libglib-2.0.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgobject-2.0.0.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgsttag-1.0.0.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstvideo-1.0.0.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgsttranscoder-1.0.0.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstrtp-1.0.0.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/gstreamer-1.0
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstanalytics-1.0.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstanalytics-1.0.0.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstmse-1.0.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstmse-1.0.0.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstapp-1.0.0.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstrtsp-1.0.0.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libintl.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstvideo-1.0.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstfft-1.0.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstadaptivedemux-1.0.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgmodule-2.0.0.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstbasecamerabinsrc-1.0.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstsctp-1.0.0.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libintl.8.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstphotography-1.0.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgsturidownloader-1.0.0.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstpbutils-1.0.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstbase-1.0.0.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstallocators-1.0.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libpcre2-posix.3.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libffi.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstcontroller-1.0.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstcodecparsers-1.0.0.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgthread-2.0.0.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libpcre2-8.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstriff-1.0.0.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstadaptivedemux-1.0.0.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstnet-1.0.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstriff-1.0.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgsturidownloader-1.0.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstbasecamerabinsrc-1.0.0.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstaudio-1.0.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstinsertbin-1.0.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstcodecs-1.0.0.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstbase-1.0.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstgl-1.0.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstgl-1.0.0.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstallocators-1.0.0.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstplayer-1.0.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstpbutils-1.0.0.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libpcre2-posix.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstsctp-1.0.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstapp-1.0.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgio-2.0.0.dylib
can't remove file /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/gstreamer-1.0
set info property list SUFeedURL = 
set info property list CFBundleShortVersionString = 25.0.1p
/Users/wooki/Applications/CrossOver.app/Contents/Info.plist does not exist!
patching /Users/wooki/Applications/CrossOver.app
/Users/wooki/Applications/CrossOver.app: replacing existing signature

renaming the app at /Users/wooki/Applications/CrossOver.app to /Users/wooki/Applications/CrossOver_patched.app
renaming the app at /Users/wooki/Applications/CrossOver_original.app to /Users/wooki/Applications/CrossOver.app
renaming successful
app version is ok: 25.0.1
it's a crossover app
file:///Users/wooki/Applications/CrossOver_original.app
Release version detected, copying DXMT
/Users/wooki/Applications/CrossOver.app//Contents/SharedSupport/CrossOver/lib/dxmt/i386-windows does not exist, creating
/Users/wooki/Applications/CrossOver.app//Contents/SharedSupport/CrossOver/lib/dxmt/i386-windows created
/Volumes/WinGo/PCGames/CrossOverApp/v0.50/x86_64-unix/winemetal.so copied
/Volumes/WinGo/PCGames/CrossOverApp/v0.50/x86_64-windows/winemetal.dll copied
/Volumes/WinGo/PCGames/CrossOverApp/v0.50/x86_64-windows/dxgi.dll copied
/Volumes/WinGo/PCGames/CrossOverApp/v0.50/x86_64-windows/d3d11.dll copied
/Volumes/WinGo/PCGames/CrossOverApp/v0.50/x86_64-windows/d3d10core.dll copied
/Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib/dxmt/i386-windows/winemetal.dll does not exist!
/Volumes/WinGo/PCGames/CrossOverApp/v0.50/i386-windows/winemetal.dll copied
/Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib/dxmt/i386-windows/dxgi.dll does not exist!
/Volumes/WinGo/PCGames/CrossOverApp/v0.50/i386-windows/dxgi.dll copied
/Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib/dxmt/i386-windows/d3d11.dll does not exist!
/Volumes/WinGo/PCGames/CrossOverApp/v0.50/i386-windows/d3d11.dll copied
/Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib/dxmt/i386-windows/d3d10core.dll does not exist!
/Volumes/WinGo/PCGames/CrossOverApp/v0.50/i386-windows/d3d10core.dll copied
Crossover/lib64/libMoltenVK.dylib copied
Crossover/lib/dxvk/i386-windows/d3d10core.dll copied
Crossover/lib/dxvk/i386-windows/d3d11.dll copied
Crossover/lib/dxvk/x86_64-windows/d3d10core.dll copied
Crossover/lib/dxvk/x86_64-windows/d3d11.dll copied
/Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib/wine/i386-windows/winemetal.dll does not exist!
Crossover/lib/wine/i386-windows/winemetal.dll copied
Crossover/lib/wine/x86_64-unix/winegstreamer.so copied
Crossover/lib/wine/x86_64-windows/winemetal.dll copied
Crossover/share/wine/wine.inf copied
removing /Users/wooki/Applications/CrossOver.app/Contents/CodeResources
removing /Users/wooki/Applications/CrossOver.app/Contents/_CodeSignature
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgmodule-2.0.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgthread-2.0.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstplayer-1.0.0.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstaudio-1.0.0.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstsdp-1.0.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstmpegts-1.0.0.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstnet-1.0.0.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstmpegts-1.0.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstrtsp-1.0.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libffi.8.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstreamer-1.0.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgsttranscoder-1.0.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstisoff-1.0.0.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstphotography-1.0.0.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstsdp-1.0.0.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstplay-1.0.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstplay-1.0.0.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgobject-2.0.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstreamer-1.0.0.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstcodecs-1.0.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libpcre2-8.0.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstwebrtc-1.0.0.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstcontroller-1.0.0.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstcodecparsers-1.0.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstbadaudio-1.0.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libglib-2.0.0.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstrtp-1.0.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstwebrtc-1.0.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgsttag-1.0.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstinsertbin-1.0.0.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstisoff-1.0.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstfft-1.0.0.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstbadaudio-1.0.0.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgio-2.0.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libglib-2.0.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgobject-2.0.0.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgsttag-1.0.0.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstvideo-1.0.0.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgsttranscoder-1.0.0.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstrtp-1.0.0.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/gstreamer-1.0
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstanalytics-1.0.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstanalytics-1.0.0.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstmse-1.0.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstmse-1.0.0.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstapp-1.0.0.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstrtsp-1.0.0.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libintl.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstvideo-1.0.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstfft-1.0.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstadaptivedemux-1.0.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgmodule-2.0.0.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstbasecamerabinsrc-1.0.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstsctp-1.0.0.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libintl.8.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstphotography-1.0.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgsturidownloader-1.0.0.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstpbutils-1.0.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstbase-1.0.0.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstallocators-1.0.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libpcre2-posix.3.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libffi.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstcontroller-1.0.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstcodecparsers-1.0.0.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgthread-2.0.0.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libpcre2-8.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstriff-1.0.0.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstadaptivedemux-1.0.0.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstnet-1.0.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstriff-1.0.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgsturidownloader-1.0.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstbasecamerabinsrc-1.0.0.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstaudio-1.0.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstinsertbin-1.0.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstcodecs-1.0.0.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstbase-1.0.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstgl-1.0.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstgl-1.0.0.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstallocators-1.0.0.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstplayer-1.0.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstpbutils-1.0.0.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libpcre2-posix.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstsctp-1.0.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstapp-1.0.dylib
removing /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgio-2.0.0.dylib
can't remove file /Users/wooki/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/gstreamer-1.0
set info property list SUFeedURL = 
set info property list CFBundleShortVersionString = 25.0.1p
/Users/wooki/Applications/CrossOver.app/Contents/Info.plist does not exist!
patching /Users/wooki/Applications/CrossOver.app
/Users/wooki/Applications/CrossOver.app: replacing existing signature

renaming the app at /Users/wooki/Applications/CrossOver.app to /Users/wooki/Applications/CrossOver_patched.app
renaming the app at /Users/wooki/Applications/CrossOver_original.app to /Users/wooki/Applications/CrossOver.app
renaming successful

**Comment by italomandara** [comment]
> Original Crossover 25.0.1 + D3DMetal + MSync: Okay~

if you used d3dmetal for testing, which isn't patched it's hardly a CXPatcher issue, maybe the bottle got corrupted, I'm still checking but things are working fine on my machine, can't replicate the issue.

unpatched crossover uses a different bottle, can i suggest to create a new bottle from scratch with the patched crossover?

**Comment by italomandara** [comment]
you're using d3dmetal there's nothing affecting that in the patch, atm, tho.

**Comment by italomandara** [comment]
I tried to run the free version of this game via dxmt on my patched crossover, the app crashed for an invalid instruction.
I guess the free version has other issues, 
can you provide a CX logfile? just to see the what else happens before that error you get? I don't have the full game so can't really debug myself.

**Comment by italomandara** [comment]
The bug had nothing to do with shader compilation, it was a problem with the gstreamer patch.
Fixed in f6faefc164f2c33cd0bc34c8138d079292ec0a6e

**Comment by nogoo** [comment]
> The bug had nothing to do with shader compilation, it was a problem with the gstreamer patch. Fixed in [f6faefc](https://github.com/italomandara/CXPatcher/commit/f6faefc164f2c33cd0bc34c8138d079292ec0a6e)

I tried LOFT2+CXPatch 6.3.5 again and there were no issues. Thank you very much for the update🎉

**Comment by italomandara** [comment]
I Had to re-open this, properly patching Gstreamer will make LOTF2 crash, this is probably a problem with Gstreamer on X86 when playing H264 streams, it needs a proper investigation @Gcenx running gst-launch-1.0 playbin uri="file:///yourfile.mp4"
plays just fine but that's the arm version of the command, this also affects other games without crashing them like Soul calibur VI where the videos are just black (also unpatched crossover has the same issue but at least it doesn't crash LOTF2)

@nogoo temporary, poor man's solution is backup all files in steamapps/common/Lords\ of\ the\ Fallen/LOTF2/Content/Movies and then remove them (e.g. zip them in that folder and remove all the mp4 files)

**Comment by AliciaBurrito** [comment]
I'm currently having the same bug, but with Honkai: Star Rail where the cutscenes just black screen. Using CXPatcher 0.6.3.6 with Crossover 25.0.1. Unpatched and prior versions of CXPatcher the cutscenes would either play out and desync, or freeze and softlock. 

I noticed in the log that it said it couldn't remove gstreamer still as seen below, so I decided to manually remove it prior to patching, though the error persisted despite the folder no longer existing - and now there is seemingly no gstreamer at all. Still a black screen too. Error log is also identical.

Easiest way to reproduce in my scenario is to get to the third phase of the "Harmonious Choir" The Great Septimus boss fight that can be re-fought.

`apply from drop action
--- BEGIN OPTIONS ---
 showDisclaimer: false
status: unpatched
skipVersionCheck: false
repatch: false
overrideBottlePath: false
copyGptk: false
patchGStreamer: true
progress: 0.0
busy: false
cxbottlesPath: /Users/${USER}/CXPBottles
patchMVK: legacyUE4
autoUpdateDisable: false
patchDXVK: false
globalEnvs:
  fastMathDisabled: false
  mtlHudEnabled: false
  dxvkAsync: true
  disableUE4Hack: false
  advertiseAVX: false
  preferredMaxFrameRate: 0.0
  metalSpatialUpscaleFactor: 1.0
  metalFXSpatial: false
  disableMVKArgumentBuffers: true
removeSignaure: true
xtLibsUrl:
  some:
    _url: file:///Users/alicia/Desktop/build-release/
    _parseInfo: nil
    _baseParseInfo: nil
copyXtLibs: true
 
 --- END OPTIONS ---
app version is ok: 25.0.1
it's a crossover app
file:///Applications/CrossOver_original.app
Crossover/lib64/libMoltenVK.dylib copied
Artifact version detected, copying DXMT
/Users/alicia/Desktop/build-release/src/winemetal/unix/winemetal.so copied
/Users/alicia/Desktop/build-release/src/winemetal/winemetal.dll copied
/Users/alicia/Desktop/build-release/src/dxgi/dxgi.dll copied
/Users/alicia/Desktop/build-release/src/d3d11/d3d11.dll copied
/Users/alicia/Desktop/build-release/src/d3d10/d3d10core.dll copied
Crossover/share/wine/wine.inf copied
/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib/wine/i386-windows/winemetal.dll does not exist!
Crossover/lib/wine/i386-windows/winemetal.dll copied
Crossover/lib/wine/x86_64-windows/winemetal.dll copied
Crossover/lib/wine/x86_64-unix/winegstreamer.so copied
preparing to remove Gstreamer files...
removing /Applications/CrossOver.app/Contents/CodeResources
removing /Applications/CrossOver.app/Contents/_CodeSignature
removing /Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgmodule-2.0.dylib
removing /Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgthread-2.0.dylib
removing /Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstplayer-1.0.0.dylib
removing /Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstaudio-1.0.0.dylib
removing /Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstsdp-1.0.dylib
removing /Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstmpegts-1.0.0.dylib
removing /Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstnet-1.0.0.dylib
removing /Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstmpegts-1.0.dylib
removing /Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstrtsp-1.0.dylib
removing /Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libffi.8.dylib
removing /Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstreamer-1.0.dylib
removing /Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgsttranscoder-1.0.dylib
removing /Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstisoff-1.0.0.dylib
removing /Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstphotography-1.0.0.dylib
removing /Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstsdp-1.0.0.dylib
removing /Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstplay-1.0.dylib
removing /Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstplay-1.0.0.dylib
removing /Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgobject-2.0.dylib
removing /Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstreamer-1.0.0.dylib
removing /Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstcodecs-1.0.dylib
removing /Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libpcre2-8.0.dylib
removing /Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstwebrtc-1.0.0.dylib
removing /Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstcontroller-1.0.0.dylib
removing /Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstcodecparsers-1.0.dylib
removing /Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstbadaudio-1.0.dylib
removing /Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libglib-2.0.0.dylib
removing /Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstrtp-1.0.dylib
removing /Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstwebrtc-1.0.dylib
removing /Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgsttag-1.0.dylib
removing /Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstinsertbin-1.0.0.dylib
removing /Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstisoff-1.0.dylib
removing /Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstfft-1.0.0.dylib
removing /Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstbadaudio-1.0.0.dylib
removing /Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgio-2.0.dylib
removing /Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libglib-2.0.dylib
removing /Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgobject-2.0.0.dylib
removing /Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgsttag-1.0.0.dylib
removing /Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstvideo-1.0.0.dylib
removing /Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgsttranscoder-1.0.0.dylib
removing /Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstrtp-1.0.0.dylib
removing /Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/gstreamer-1.0
removing /Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstanalytics-1.0.dylib
removing /Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstanalytics-1.0.0.dylib
removing /Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstmse-1.0.dylib
removing /Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstmse-1.0.0.dylib
removing /Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstapp-1.0.0.dylib
removing /Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstrtsp-1.0.0.dylib
removing /Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libintl.dylib
removing /Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstvideo-1.0.dylib
removing /Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstfft-1.0.dylib
removing /Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstadaptivedemux-1.0.dylib
removing /Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgmodule-2.0.0.dylib
removing /Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstbasecamerabinsrc-1.0.dylib
removing /Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstsctp-1.0.0.dylib
removing /Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libintl.8.dylib
removing /Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstphotography-1.0.dylib
removing /Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgsturidownloader-1.0.0.dylib
removing /Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstpbutils-1.0.dylib
removing /Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstbase-1.0.0.dylib
removing /Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstallocators-1.0.dylib
removing /Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libpcre2-posix.3.dylib
removing /Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libffi.dylib
removing /Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstcontroller-1.0.dylib
removing /Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstcodecparsers-1.0.0.dylib
removing /Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgthread-2.0.0.dylib
removing /Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libpcre2-8.dylib
removing /Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstriff-1.0.0.dylib
removing /Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstadaptivedemux-1.0.0.dylib
removing /Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstnet-1.0.dylib
removing /Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstriff-1.0.dylib
removing /Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgsturidownloader-1.0.dylib
removing /Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstbasecamerabinsrc-1.0.0.dylib
removing /Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstaudio-1.0.dylib
removing /Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstinsertbin-1.0.dylib
removing /Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstcodecs-1.0.0.dylib
removing /Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstbase-1.0.dylib
removing /Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstgl-1.0.dylib
removing /Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstgl-1.0.0.dylib
removing /Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstallocators-1.0.0.dylib
removing /Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstplayer-1.0.dylib
removing /Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstpbutils-1.0.0.dylib
removing /Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libpcre2-posix.dylib
removing /Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstsctp-1.0.dylib
removing /Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgstapp-1.0.dylib
removing /Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/libgio-2.0.0.dylib
can't remove file /Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64/gstreamer-1.0
set info property list CFBundleShortVersionString = 25.0.1p
patching /Applications/CrossOver.app
/Applications/CrossOver.app: replacing existing signature

renaming the app at /Applications/CrossOver.app to /Applications/CrossOver_patched.app
renaming the app at /Applications/CrossOver_original.app to /Applications/CrossOver.app
renaming successful`

**Comment by nogoo** [comment]
> I Had to re-open this, properly patching Gstreamer will make LOTF2 crash, this is probably a problem with Gstreamer and crossover [@Gcenx](https://github.com/Gcenx) running gst-launch-1.0 playbin uri="file:///yourfile.mp4" plays just fine Soul calibur VI where the videos are just black (also unpatched crossover has the same issue but at least it doesn't crash LOTF2) when played in the game.
> 
> [@nogoo](https://github.com/nogoo) first try to uninstall gstreamer from brew and retry... (but you still have to install gstreamer via macos installer) if that doesn't work: temporary, poor man's solution is backup all files in steamapps/common/Lords\ of\ the\ Fallen/LOTF2/Content/Movies and then remove them (e.g. zip them in that folder and remove all the mp4 files)`brew uninstall gstreamer`

I have installed the latest Mac 26 and CXPatch 0.6.4, and the problem before LOFT2 has reappeared. 
The issue of "Brew uninstall gstreamer and install Mac .pkg version" still persists. 
I tried deleting the files under Movies, but how can I really solve the problem of MP4 not playing? Later, I want to try changing the encoding of the mp4 file.

**Comment by nogoo** [comment]
Okay，I have converted all mp4 files to av1 encoding format. Although the game still has a black screen, you can see white text information and synchronized voice. You can also enter the game through shaders.
I don't know if there are any surprises in other formats. I will try them when I have time
