### ISSUE TITLE
OW2 windows 7

### ISSUE THREAD

**Issue by Devolla** [italomandara/CXPatcher#54]
for whatever reason it says I need windows 10 while I downloaded the windows 10 version

**Comment by sawawas** [comment]
did u follow this https://youtu.be/AxKK3ctISnk 
only way overwatch is working without missing elements too, i cant remember if a wine window popped up that you had to change from windows 7 to 10 but you need to click apply then ok

**Comment by Gcenx** [comment]
Hum Win10 bottle is getting screwed up and reporting as Win8.1, I'll look into this

**Comment by FredvdEijkel** [comment]
I had the same problem when trying to install overwatch 2 (unsupported OS version 8.1).
After adding `Battle.net.exe` and `Battle.net Launcher.exe` (from `Program Files (x86)\Battle.net`) to Wine configurations > Applications, I was able to install overwatch 2 without the unsupported OS version message showing.

**Comment by Gcenx** [comment]
We’ll have this resolved in the next CXPatcher release, I’d forgotten some of the updated keys required additional patches 🤦‍♂️

**Comment by Naicriz** [comment]
I have the same problem, clean install of crossover and gptk with cxpatcher, install the w10 64bit of steam and when launching it said that is w8.1.
Also, every time i tried to run the witcher 3 and play it would freeze when i hit an enemy or they hit me, i tryied so many things and still happening :(.

**Comment by Gcenx** [comment]
> I have the same problem, clean install of crossover and gptk with cxpatcher, install the w10 64bit of steam and when launching it said that is w8.1.
> Also, every time i tried to run the witcher 3 and play it would freeze when i hit an enemy or they hit me, i tryied so many things and still happening :(.

Please make a new issue for Witcher3 and provide as much info as possible

**Comment by unknown0w0** [comment]
To fix this you have to go in to Wine Config and manually change it from 
![Screenshot 2023-07-27 at 10 19 21 PM](https://github.com/italomandara/CXPatcher/assets/54235484/266cfa39-21ae-4a57-b493-5761cecb6a05)

**Comment by unknown0w0** [comment]
> for whatever reason it says I need windows 10 while I downloaded the windows 10 version
                   .
Fix above?/I\
                   I

**Comment by italomandara** [comment]
This is fixed by using a separate dxvk patched app
